### ISSUE TITLE
Environment Wrapping

### ISSUE THREAD

**Issue by marvinweber** [micheltokic/stable_baselines_model_based_rl#10]
## ToDos
- [x] Basic Class for Wrapping
- [x] Interfaces for Handling Reward/Done
- [x] Utility classes/methods for mapping spaces between internal and gym "version", etc.
- [x] Reset Handling
- [x] Update Sampler to use new utility methods / classes
- [x] Allow input of "Gym Actions" for step() function (currently, for discrete actions, our internal (the one also used in csv files) format is expected; both formats should be possible).
- [ ] Tests

---
## Reset Handling Possibilities
- DEFAULT: random values (observation_space.sample())
- user-defined values (static, always the same)
- random start from an episode
- user defined function (must return required amount of observations to fill the buffer)
