### ISSUE TITLE
Data Output / Storage

### ISSUE THREAD

**Issue by marvinweber** [micheltokic/stable_baselines_model_based_rl#11]
Currently everything is stored in a folder within the project directory.

## Todos
- [x] Output location should be configurable
- [x] ~Default output location (if none given): Current working directory (?). For a user of the framework it doesn't make sense if outputs are stored within the framework source directories~ -> output directory should always be provided
- [x] Debug Output / Renaming (with loss and lag in directory name) should be an optional (debugging) feature
