### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by marvinweber** [micheltokic/stable_baselines_model_based_rl#5]
## Todo
- [x] Documentation of the Configuration File -> documentation for every part/section of the config file required
- [x] Documentation of distinct parts and components of the framework (including usage examples)
  - [x] Sampling
  - [x] Dynamic Model Creation: General
  - [x] Dynamic Model Creation: Artificial Noise
  - [x] Model Wrapping
  - [x] Policy Training (?)
- [x] ...

---
- [x] Optional: PDF Export of Documentation
